version: '3.8'

services:
  backend_service:
    build: .
    container_name: backend_service
    command: python main.py
    ports:
      - "8088:8080"  # Adjust the port as needed

  locust_service:
    build: .
    container_name: locust_service
    command: locust -f locustfile.py --host=http://0.0.0.0:8089
    ports:
      - "8089:8089"
    depends_on:
      - backend_service